### ISSUE TITLE
How to add custom ignore paths?

### ISSUE THREAD

**Issue by cglai** [cweagans/docker-bg-sync#17]
In the _sync.sh_, I saw `# Files to ignore`, and yes, files in path like _.git/_ were not synced into app container.

However, I couldn't find where to add custom ignore paths (in my example, _.phpintel_) in README.

So, can u add one more start option to support this without fork this repo and rebuild a container by modify _sysc.sh_?

**Comment by cweagans** [comment]
Yep, you can use `SYNC_EXTRA_UNISON_PROFILE_OPTS` to specify extra lines to add to your Unison profile. Just mimic the other lines that are there and they will be skipped.

**Comment by cglai** [comment]
Sorry it was I that unfamiliar with Unison configuration before, and I didn't recognize this option.

I used `SYNC_EXTRA_UNISON_PROFILE_OPTS` option when start this container like this:

``` shell
-e SYNC_EXTRA_UNISON_PROFILE_OPTS="ignore = Path .path1/*"
```

And in _/home/{USER}/.unison/default.prf_, the identical string value of that option was appended in, and it works.

However, when I add one more path to be ignored, like
```
-e SYNC_EXTRA_UNISON_PROFILE_OPTS="ignore = Path .path1/* \n ignore = Path .path2/*"

# Or
-e SYNC_EXTRA_UNISON_PROFILE_OPTS="ignore = Path .path1/*" \
-e SYNC_EXTRA_UNISON_PROFILE_OPTS="ignore = Path .path2/*"    # !!! overwrote
```
It didn't work this time, whether `\n` exist or not.

>  If you have more than one option that you want to add, simply make this a multiline string.

So, what a _multiline string_ actually look like?

Thx! :)

**Comment by cweagans** [comment]
@leymannx has a good example here: https://github.com/leymannx/dockerix/blob/master/docker-compose.yml#L39-L50

If there's something that could go into the documentation to make this clearer, PRs are always appreciated :) Otherwise, I'll get around to it someday.

**Comment by cglai** [comment]
All right ... It turns out I thought this too complicated because there's the simplest way to set multiline values for environment option when executing `docker run`:

 ``` shell
docker run \

...

-e SYNC_EXTRA_UNISON_PROFILE_OPTS="ignore = Path path1/*
ignore = Path path2/*
ignore = Path path3/*" \

...
```

Besides, <https://github.com/leymannx/dockerix/blob/master/docker-compose.yml#L39-L50> also remind me to achieve multiline string setting when using `docker-compose`.

Thx again, problem solved. :)
