### ISSUE TITLE
On Windows, the container is only synced once when it starts

### ISSUE THREAD

**Issue by patriceckhart** [cweagans/docker-bg-sync#31]
On Windows the sync works. however, it only works once. If a change is made to the host, nothing will be synced. If you restart the container, the changes are synced. It works fine on Mac. 

Can you help?

**Comment by cweagans** [comment]
I would not recommend using this on Windows. If you run Docker in WSL, plain bind mounts will be much faster and more reliable than this method. I would also recommend looking into [Mutagen](https://mutagen.io) on Mac environments. It syncs faster than Unison and is also more reliable with the downside of having to do some one-time setup on the host. If you're using [ddev](https://github.com/drud/ddev/) for your local environment (which I highly recommend), this functionality is built in and you just have to turn it on (no host setup required): https://ddev.readthedocs.io/en/latest/users/performance/#using-mutagen

**Comment by cweagans** [comment]
(just to clarify, I would not recommend using this repo in general at this point)

**Comment by patriceckhart** [comment]
Thank you. I don't use ddev. I have an lightweight custom image in development and also in production. But I'll try it with mutagen.
