### ISSUE TITLE
Only syncs once?

### ISSUE THREAD

**Issue by mike-potter** [cweagans/docker-bg-sync#8]
Gave this a try using the example configuration.  It eventually synced everything from /source into /var/www.  However, after the sync was done, I edited a file on my local Mac (that is in the /source mount) and it was never synced to /var/www.

I ssh'd to the sync container and verified that the /source/README.txt file was changed and the /var/www/README.txt was still the original.

Is there a polling interval to set here or is there an issue with the file watching?

Maybe the issue is that the directory on the Mac is mounted into the docker-machine using docker-machine-nfs? Which maybe doesn't generate the events needed here?

**Comment by mike-potter** [comment]
The problem might be that we are using VirtualBox.  Even when I remove the NFS and try to use the native file system it appears that vboxfs doesn't fire the events.

**Comment by cweagans** [comment]
Sounds like an issue with the filesystem events. I doubt this will work in docker-machine. It was built to work around osxfs slowness in Docker for Mac. Conveniently, osxfs propagates filesystem events into their VM, which allows this container to work properly.

**Comment by mike-potter** [comment]
Yep, the issue is with docker-machine.  You might make it clearer on the project page that this repo only works for Docker for Mac.

**Comment by alexromero88** [comment]
I think I'm having the same problem as Mike, but I'm definitely using Docker for Mac. I can see:

```
osxfs                   465.6G    371.4G     80.5G  82% /source
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/sda1                73.1G     10.2G     59.1G  15% /Users/aromero2/dev/iop/Common
```

/Users/aromero2/dev/iop/Common is the sync destination. Any idea?
